### ISSUE TITLE
Chocolatey uses a weird installation path for Neovim

### ISSUE THREAD

**Issue by audreytoskin** [tricktux/choco-neovim#1]
I just installed neovim 0.2.1-25-g2e3b78d1 from the Chocolatey CLI 0.10.6.1 on Windows 10 x86_64 Home Edition version 1703, OS Build 15063.332.

nvim and nvim-qt seem to work as usual, except that your `choco` script used a strange default installation path: `C:\Windows\SysWOW64\Get-ToolsLocation\neovim\Neovim`. Why would it be installed anywhere other than `Program Files`? And if installing to a nonstandard location, why not add it to the Path environment variable?

I thought at first that the Chocolatey installer script was broken, and it took a while to find the nvim executable.

**Comment by tricktux** [comment]
>nvim and nvim-qt seem to work as usual, except that your choco script used a strange default installation path: C:\Windows\SysWOW64\Get-ToolsLocation\neovim\Neovim

I have to investigate on this one.  I pushed an update but I am not 100% sure it will fix this issue. Can you give it a try and report. 
>Why would it be installed anywhere other than Program Files?

So that it doesnt require Admin privileges.

>And if installing to a nonstandard location, why not add it to the Path environment variable?

Can certainly be done.

Thanks

**Comment by audreytoskin** [comment]
I'm not sure if I can properly test your update.

I ran `choco uninstall -y neovim`, and it *says* it successfully removed the package. Yesterday I'd manually added the Neovim path to my Path user environment variable, so after uninstalling, I also deleted this entry from Path.

However, when I logged out and logged back in, I noticed the Neovim somehow reappeared in my Path, and the `C:\Windows\SysWOW64\Get-ToolsLocation\neovim` installation is still there. I tried to `choco uninstall` again, but choco reports that the package has already been removed. But when I execute `nvim`, the application does still launch.

So... that's weird, right? I can't get a clean test for reinstalling the updated package if I can't fully *uninstall*, right?

**Comment by tricktux** [comment]
Since the installation had issues the uninstallation will as well. For now you could manually completely remove neovim from your system, and possibly the path section as well. And then try to install it again. Once it has installed properly you could add it to the path. Since now it will have a sane installation location.

**Comment by audreytoskin** [comment]
Okay, I deleted the whole Neovim directory, and the Path entry, and a couple Registry entries.

I then rebooted and verified that Neovim was completely removed. When I reinstalled, though, it installed in the same directory as before, and still did not update the Path variable.

Does Chocolatey locally cache the package sources information...? On my Linux machine, I might do something like `sudo dnf makecache` to refresh the database of available packages, but I don't see a way to do that in Chocolatey.

**Comment by tricktux** [comment]
Did you installed using `choco install neovim` or using `choco install neovim --pre`. I should have specified this before. Fix for the released version still has not being updated. In case you used the later I will have to keep investigating. If not please repeat using the later command.

**Comment by audreytoskin** [comment]
Okay, with the `--pre` option, Neovim installs under `C:\tools\neovim` . This directory makes a little more sense to me, and this way Chocolatey actually reports the full installation path :)

(Before I believe choco only said it was installed to `Get-ToolsLocation`, which I'd never heard of before.)

Chocolatey also reports that "Environment Vars (like PATH) have changed." But I think the only new environment variable you've added so far was `ChocolateyToolsLocation`, right? I started a new PowerShell, but it didn't recognize `nvim` as a valid command until I added `C:\tools\neovim\Neovim\bin` to my Path... I would understand if you just haven't added that to your package spec yet, but I wasn't sure if it was supposed to add to the Path yet. Just making sure we're on the same page :)

**Comment by tricktux** [comment]
Yes I haven't added the path part yet. Will soon.

**Comment by ferventcoder** [comment]
Edit: just waking up and didn't make it all the way down the thread. Looks like you already made this determination.

~~In powershell, run the following: `ls env:` (don't post the results here).~~

~~Look for something like `ChocolateyToolsLocation` - it should be set to this weird value. Please change that value in the environment variables to where you would want installs of tools like this to go.~~

**Comment by ferventcoder** [comment]
You might upgrade to 0.10.7, I'm guessing you got hit by a bug in 0.10.4-0.10.5 where virtualization comes on due to the manifest file not being next to choco.exe the first time you run it - upgrade resolves this

**Comment by tricktux** [comment]
Correct. I have not added to neovim to `PATH` during install. So I'm glad is working as it should now.
