### ISSUE TITLE
`choco install neovim --pre` does not install prerelease version

### ISSUE THREAD

**Issue by corbob** [tricktux/choco-neovim#14]
The mentioned method of getting nightly appears to be pulling stable.

![image](https://user-images.githubusercontent.com/30301021/60760196-21361e00-9fe6-11e9-9a2c-ee5e0824ce49.png)

**Comment by tricktux** [comment]
Thanks for the report. I tried fixing it in this 0.3.8 release but it broke because of checksum mismatch. I will look into it.
