### ISSUE TITLE
shouldn't a shim be generated?

### ISSUE THREAD

**Issue by fpn** [tricktux/choco-neovim#2]
0.2.1.329-beta

nvim and nvim-qt are not in the path - it seems the shims are missing?
I see them in : C:\tools\neovim\Neovim\bin

**Comment by tricktux** [comment]
Excellent question! @ferventcoder. I was thinking of manually adding the location of the install to the path but if a shim where to be created would be a lot better. After reading [here](https://chocolatey.org/docs/features-shim) I think that it has to do with neovim not being installed in the default location but rather `Tools` location. Its not very clear in the documentation.

**Comment by ferventcoder** [comment]
@rmolin88 thanks, you are correct it is not clear there. We are working on conceptual/narrative docs. https://github.com/chocolatey/choco/issues/1303, and specifically this comment (https://github.com/chocolatey/choco/issues/1303#issuecomment-303804561):

## Packaging Patterns - Installing a Zip

[..snip..]

### Where to Unpack

With installing a zip, explain Get-ToolsLocation and why Program Files is not the best idea.

### Other Notes
Normally you would just let a zip unpack into the package directory (the `$toolsDir` variable seen in chocolateyInstall.ps1 after running `choco new <pkgid>`). This ensures that exe files are automatically shimmed and available to run immediately after the install.

However in some scenarios you may have other packages that will install components (like `pkgid-someplugin`) and want to maintain all of that outside of the packaging directories. Or for some other performance or pathing reason. In those cases we recommend installing to the [Chocolatey Tools Location](https://chocolatey.org/docs/helpers-get-tools-location).

~~~powershell
$unpackDirectory = Join-Path Get-ToolsLocation $packageName
~~~

By default Chocolatey Tools Location is `c:\tools`, but it can be whatever the user desires for it to be. We don't recommend attempting to access `$env:ChocolateyToolsLocation` directly as it may not be set yet or may be needing to be upgraded from another value (the validator on the community repo will also flag your package for required fixes if you do use that variable). That is all done when you call `Get-ToolsLocation`, so we recommend you simply call that function instead.

When you unpack outside of packaging directory, you need to manage ensuring any executables are on the PATH and available. This is already done automatically with exes that are in the package directory. 

* For adding/updating PATH, see [`Install-ChocolateyPath`](https://chocolatey.org/docs/helpers-install-chocolatey-path)
* For creating a shim from a location outside of the package, see [`Install-BinFile`](https://chocolatey.org/docs/helpers-install-bin-file)

### Availability
Keep in mind with updating PATH that it does not take effect in the current process. Once choco.exe exits, that information is available and set in the registry, but you would need to close and reopen your command shell for it to "see" those changes. There is also `refreshenv` you can run from cmd.exe (you can also run it from powershell.exe ***if*** you have the Chocolatey PowerShell profile and tab completion installed). The trick is your users have to run this (and know to run this, choco does mention it if there are PATH updates during the install). 

If you let Chocolatey create a shim or if you create a shim with `Install-BinFile`, that means the app will be available as soon as choco exits.

**Comment by tricktux** [comment]
@ferventcoder Thanks for the suggestions. Finally sat down to read the docs. It makes sense now. I am using the shims and they seem to be working!
