### ISSUE TITLE
nvim not in PATH after installing

### ISSUE THREAD

**Issue by trusktr** [tricktux/choco-neovim#4]
Hello, I `choco install neovim`ed, then restarted CMD, and then it says

```
C:\>nvim
'nvim' is not recognized as an internal or external command,
```

I know I can modify PATH manually, but ideally the install should do it.

**Comment by trusktr** [comment]
I see it installs `C:\tools\neovim\Neovim\bin\nvim`. Is the install supposed to add that to PATH? (or link it to a common place?)

**Comment by tricktux** [comment]
Yes this is an issue. Currently, the installation doesnt add it to the path. You'll have to manually do this. And that is the correct location: `C:\tools\neovim\Neovim\bin\nvim.exe`. Which translates to adding `C:\tools\neovim\Neovim\bin` to the path for it to function properly. Meaning finding `clipboard` and stuff like that.

**Comment by jasonmcboyd** [comment]
Is there any specific reason it cannot be installed in C:\ProgramData\Chocolatey like many other applications? That would solve both, the PATH issue and shim issue raised in the other open issue.

**Comment by tricktux** [comment]
I cant remember but @ferventercoder suggested it this way. It makes more sense. Anyways I've fixed the issue. Thanks for the feedback.
