### ISSUE TITLE
neovim-git: download from github instead of appveyor

### ISSUE THREAD

**Issue by justinmk** [tricktux/choco-neovim#5]
I noticed that the neovim-git script seems to download from appveyor:

https://github.com/rmolin88/choco-neovim/blob/4b89df16a370bb81ceb25603f9e24930a666594d/neovim-git/tools/chocolateyinstall.ps1#L5

It could instead point to these URLs:

https://github.com/neovim/neovim/releases/download/nightly/nvim-win32.zip
https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip

That might be faster and more reliable than appveyor. 

The `nightly` [release](https://github.com/neovim/neovim/releases) is updated daily by a script.

**Comment by tricktux** [comment]
Thanks for the suggestion and for taking time. Keep `neovim` rocking @justinmk !!!
