### ISSUE TITLE
Invoking ShimGen version of win32yank.exe leaves dangling consoles

### ISSUE THREAD

**Issue by DustinVenegas** [tricktux/choco-neovim#6]
- **Which Package?** Chocolatey version 0.2.2.20180416
  - **Summary?** Calling shimgen generated binaries in the PATH from nvim-qt leaves cmd.exe Window instances open _per call_
  - **Description?** Vim has an option to `set clipboard+=unnamedplus`. This should attempt to bridge the Windows Clipboard to Neovim's `+` register. Regretfully, each call to the ShimGen generated `win32yank.exe` binary leaves `cmd.exe` Window instances open _after each copy or paste operation_.
  - **Repro Steps?** 
    * Ensure Chocolatey ShimGen generated win32yank.exe binary is in the PATH. In PowerShell, `Get-Command win32yank.exe` should return the ShimGen binary path (`c:\ProgramData\chocolatey\bin\win32yank.exe`)
    * Ensure neovim has `set clipboard+=unnamedplus` in a `nvim-qt` instance (ShimGen or direct; doesn't matter here)
    * Yank and paste lines in a `nvim-qt.exe` instance. 
    * Observe multiple cmd.exe windows from ShimGen are left open. Each is the ShimGen `win32yank.exe`
    * If you rename or delete the ShimGen generated `win32yank.exe`, and default to the bundled version in Neovim (in your PATH) then yank and paste work correctly. The ShimGen version is definitely doing something different. 

I'm unsure if the package is missing options for creating ShimGen binaries correctly, or if the package should fall-back to user-level PATH variables. 

Related to lukesampson/scoop/pull/2206

**Comment by tricktux** [comment]
Thanks for the detailed issue report and for the pull. I took a different approach however. Thanks!
