### ISSUE TITLE
neovim 0.3.0 fails to open files when filenames passed as arguments

### ISSUE THREAD

**Issue by DustinVenegas** [tricktux/choco-neovim#8]
When passing in a filename to nvim-qt, it ignores the parameter. Opening by filename works great using nvim.exe directly. 

**Repro Steps**
  - Install version 0.3.0 from Chocolatey
  - Attempt to open a file in neovim-qt `nvim-qt foo.txt`
    - Note that `foo.txt` was never opened in nvim-qt
  - Attempt to open a file in nvim. `nvim foo.txt`.
    - note it worked fine.

**Comment by tricktux** [comment]
This is a [neovim-qt](https://github.com/equalsraf/neovim-qt) issue which has already being reported [#417](https://github.com/equalsraf/neovim-qt/issues/417) and [#416](https://github.com/equalsraf/neovim-qt/issues/416).

Thanks for reporting the issue.

**Comment by w1mb0r** [comment]
It seems like the file isn't opened but in fact the file is opened as buffer 2 and you get to see buffer 1 which is an empty buffer.
use ":ls" to see the buffers, ":bd" to close the current buffer, ":b1" or ":b2" to switch to the buffer with corresponding number.
